services:
  App\Admin\CategoriesAdmin:
    arguments: [~, App\Entity\Category,~]
    tags:
      - {name: sonata.admin, manager_type: orm, label: Categories, group: Product List}
    public: true

  App\Admin\ProductsAdmin:
    arguments: [~, App\Entity\Product,~]
    tags:
      - {name: sonata.admin, manager_type: orm, label: Products, group: Product List}
    public: true

  App\Admin\FeedbackRequestAdmin:
    arguments: [~, App\Entity\FeedbackRequest,~]
    tags:
      - {name: sonata.admin, manager_type: orm, label: Feedback, group: Feedback}
    public: true

  App\Admin\UsersAdmin:
    arguments: [~, App\Entity\User,~]
    tags:
      - {name: sonata.admin, manager_type: orm, label: Users, group: User List}
    public: true

  App\Admin\ProductImagesAdmin:
    arguments: [~, App\Entity\ProductImage, ~]
    tags:
    - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}
    public: true