# app/config/config.yml
fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: noreply@eshop.com
    sender_name: "HR"

  registration:
      confirmation:
          enabled: true
      form:
          type: App\Form\RegistrationType
  profile:
      form:
          type: App\Form\ProfileType